server:
    port: 9005

spring: 
  application:
     name : masterdata-service
      
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default-zone: http://localhost:8761/eureka/
  instance:
    hostname: localhost