//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.6 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.05.12 at 03:47:20 PM WIB 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "T24WebServicesImpl")
package com.accservice.accservice.stub;
