server:
    port: 9099

spring: 
  application:
     name : tws-coba
      
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default-zone: http://localhost:8761/eureka/
  instance:
    hostname: localhost