//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.6 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.05.10 at 10:25:48 AM WIB 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "T24WebServicesImpl")
package com.cifservice.cifservice.stub;
