server:
    port: 9091

spring: 
  application:
     name : region-service

#   datasource: 
#     url : jdbc:mysql://localhost:8080/db_exa
#     username : root
#     password : root
#   jpa: 
#     properties:
#       hibernate:
#         dialect: org.hibernate.dialect.MySQL5Dialect
#         connection: 
#           characterEncoding: UTF-8
#           CharSet: UTF-8
#           useUnicode: true
#     show-sql: true 
#     hibernate:
#       ddl-auto: none  

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default-zone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
